#!/usr/bin/env bash
#
# macos-defaults
#
# Set some reasonable macOS defaults.
#
# Thanks to Mathias Bynens' macOS defaults script:
# - https://github.com/mathiasbynens/dotfiles/blob/master/.macos

PROG=${0##*/}

# macOS only...
if [[ $(uname) != "Darwin" ]]
then
  echo "$PROG script is for macOS only!"
  exit 1
fi

# macOS Big Sur only...
if ! [[ $(sw_vers -productVersion) =~ ^11\.? ]]
then
  echo "$PROG script is intended for macOS versions 11.x"
  exit 1
fi

# Ask for the administrator password upfront.
sudo -v

# General - UI/UX
# ----------------------------------------------------------------------------

# Set hostname. Only the user-friendly name (computer name), the local
# (Bonjour) host name and NetBIOS name get set by the Sharing preference pane.
sudo scutil --set ComputerName titan
sudo scutil --set LocalHostName titan
sudo scutil --set HostName titan
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "titan"

# Disable open and close window animations (default: not set).
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -boolean false

# Set Sidebar icon size to small.
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -integer 1

# Disable focus ring animation (default: not set).
defaults write NSGlobalDomain NSUseAnimatedFocusRing -boolean false

# Save new documents to disk (not to iCloud) (default: not set).
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -boolean false

# Reduce transparency in macOS.
defaults write com.apple.universalaccess reduceTransparency -boolean true

# Desktop & Screen Saver
# ----------------------------------------------------------------------------

# Save screen capture in PNG format (default: nost set).
defaults write com.apple.screencapture type -string "png"

# Disable showing floating thumbnail (default: not set).
defaults write com.apple.screencapture show-thumbnail -boolean false

# Disable shadows on screen captures (default: not set).
defaults write com.apple.screencapture disable-shadow -boolean true

# Dock
# ----------------------------------------------------------------------------

# Minimize windows using the "Scale" effect.
defaults write com.apple.dock mineffect -string "scale"

# Minimize windows into their application icon.
defaults write com.apple.dock minimize-to-application -boolean true

# Set the icon size of Dock items to 48 pixels (default: not set).
defaults write com.apple.dock tilesize -integer 48

# Finder
# ----------------------------------------------------------------------------

# Disable all window and Get Info animations (default: not set).
defaults write com.apple.finder DisableAllAnimations -boolean true

# New windows show home directory.
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"

# Show icons on the desktop for external disks.
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -boolean true

# Show icons on the desktop for removable media.
defaults write com.apple.finder ShowRemovableMediaOnDesktop -boolean true

# Show status bar.
defaults write com.apple.finder ShowStatusBar -boolean true

# Safari
# ----------------------------------------------------------------------------

# Disable opening "safe" files automatically after downloading.
defaults write com.apple.Safari AutoOpenSafeDownloads -boolean false

# Set home page to `about:blank`.
defaults write com.apple.Safari HomePage -string "about:blank"

# Show status bar.
defaults write com.apple.Safari ShowStatusBar -boolean true

# Terminal
# ----------------------------------------------------------------------------

# Add terminal profiles for the Solarized Dark and Solarized Light color
# schemes.
open "../Terminal/Solarized Dark.terminal"
sleep 1
open "../Terminal/Solarized Light.terminal"
sleep 1

# Make Solarized Light the default terminal profile.
defaults write com.apple.Terminal "Default Window Settings" -string "Solarized Light"
defaults write com.apple.Terminal "Startup Window Settings" -string "Solarized Light"

# Music
# ----------------------------------------------------------------------------

# Play while converting files (default: true).
defaults write com.apple.Music playWhileEncoding -boolean false

# Preload files into memory (default: false).
defaults write com.apple.Music preloadFilesIntoMemory -boolean true
