#!/usr/bin/env bash
#
# setup
#
# This script will pull down the latest versions of the dotfiles and copy them
# to your home directory.

install_dotfiles() {
  rsync -avh \
    --exclude ".git/" \
    --exclude "Terminal/" \
    --exclude "script/" \
    --exclude ".DS_Store" \
    --exclude "LICENSE.txt" \
    --exclude "README.md" \
    --exclude "login.sql" \
    --no-perms \
    . ~
  source ~/.bash_profile
}

PROG=${0##*/}

# Check for git.
command -v git >/dev/null 2>&1 || { echo "$PROG: git: command not found"; exit 1; }

# Pull down the latest changes.
echo "Syncing dotfiles..."
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit
git pull origin master

# Verify that the user wants to continue before potentially overwriting files.
read -r -p "This may overwrite existing files. Are you sure? (y/n) " -n 1
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  install_dotfiles
fi

unset install_dotfiles
